# Homework 4

In [0]:
import math
import numpy as np

## Problem 1

A convolution is performed of an input matrix given a kernel. We iterate over the matrix with the kernel. At each iteration we multiply every element of the kernel with its corresponding element in the matrix and sum them together resulting in a final value. An element of the final, output matrix.

In [0]:
# Applies an image convolution to a matrix given a kernel.
def conv2d(input_mat, kernel_mat):
  # Catch empty matrices.
  if len(kernel_mat) == 0 or len(input_mat) == 0:
      raise ValueError('Empty input matrix(s)')

  # Initialize.
  input_mat_width, input_mat_height  = len(input_mat[0]), len(input_mat)
  kernel_mat_width, kernel_mat_height  = len(kernel_mat[0]), len(kernel_mat)

  # Matrices must be square by the hw description.
  if kernel_mat_width != kernel_mat_height or input_mat_width != input_mat_height:
    raise ValueError('Matrices are not square')

  # Catch a kernel that is too large or matrix that's too small.
  if kernel_mat_width > input_mat_width or kernel_mat_height > input_mat_height:
    raise ValueError('Kernel size is too large for the matrix')

  # Calculate output matrix dimensions.
  width_reduction, height_reduction = kernel_mat_width-1, kernel_mat_height-1
  output_mat_width, output_mat_height = input_mat_width-width_reduction, input_mat_height-height_reduction
  output_mat = np.zeros((output_mat_height, output_mat_width))

  # Apply convolution to input matrix with kernel matrix.
  for i in range(output_mat_height):
    for j in range(output_mat_width):
      sum = 0
      
      # Apply kernel and save resulting matrix.
      for k in range(kernel_mat_height):
        for l in range(kernel_mat_width):
          sum += input_mat[i+k][j+l]*kernel_mat[k][l]
      output_mat[i][j] = sum
  
  return output_mat

### Test cases

$input = 
\begin{pmatrix}
0 & 1 & 2 & 3 & 4\\
5 & 6 & 7 & 8 & 9\\
0 & 1 & 2 & 3 & 4\\
5 & 6 & 7 & 8 & 9\\
0 & 1 & 2 & 3 & 4
\end{pmatrix}
\,\,\,\,\,\,\,\,\,\,\,\,
kernel = 
\begin{pmatrix}
0 & -1\\
-1 & 0
\end{pmatrix}$

In [38]:
# hw test case
input_mat = np.array([[0, 1, 2, 3, 4],
                      [5, 6, 7, 8, 9],
                      [0, 1, 2, 3, 4],
                      [5, 6, 7, 8, 9],
                      [0, 1, 2, 3, 4]])
kernel_mat = np.array([[0, -1],
                       [-1, 0]])
expected_mat = np.array([[-6, -8, -10, -12],
                         [-6, -8, -10, -12],
                         [-6, -8, -10, -12],
                         [-6, -8, -10, -12]])

output_mat = conv2d(input_mat, kernel_mat)

print(output_mat)
if np.array_equal(output_mat, expected_mat):
  print("Correct output!\n")
else:
  print("Incorrect output!\n")

[[ -6.  -8. -10. -12.]
 [ -6.  -8. -10. -12.]
 [ -6.  -8. -10. -12.]
 [ -6.  -8. -10. -12.]]
Correct output!



$input = 
\begin{pmatrix}
1 & 2 & 1 & 2\\
2 & 1 & 2 & 1\\
1 & 2 & 1 & 2\\
2 & 1 & 2 & 1
\end{pmatrix}
\,\,\,\,\,\,\,\,\,\,\,\,
kernel = 
\begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix}$

In [39]:
# test case 1
input_mat = np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]])
kernel_mat = np.array([[1, 0],
                       [0, 1]])
expected_mat = np.array([[2, 4, 2],
                         [4, 2, 4],
                         [2, 4, 2]])

output_mat = conv2d(input_mat, kernel_mat)

print(output_mat)
if np.array_equal(output_mat, expected_mat):
  print("Correct output!\n")
else:
  print("Incorrect output!\n")

[[2. 4. 2.]
 [4. 2. 4.]
 [2. 4. 2.]]
Correct output!



$input = 
\begin{pmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{pmatrix}
\,\,\,\,\,\,\,\,\,\,\,\,
kernel = 
\begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix}$

In [40]:
# test case 2
input_mat = np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])
kernel_mat = np.array([[1, 0],
                       [0, 1]])
expected_mat = np.array([[2, 0, 0],
                         [0, 2, 0],
                         [0, 0, 2]])

output_mat = conv2d(input_mat, kernel_mat)

print(output_mat)
if np.array_equal(output_mat, expected_mat):
  print("Correct output!\n")
else:
  print("Incorrect output!\n")

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
Correct output!



$input = 
\begin{pmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{pmatrix}
\,\,\,\,\,\,\,\,\,\,\,\,
kernel = 
\begin{pmatrix}
1 & -1\\
-1 & 0
\end{pmatrix}$

In [41]:
# test case 3
input_mat = np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])
kernel_mat = np.array([[1, -1],
                       [-1, 0]])
expected_mat = np.array([[ 1, -1,  0],
                         [-1,  1, -1],
                         [ 0, -1,  1]])

output_mat = conv2d(input_mat, kernel_mat)

print(output_mat)
if np.array_equal(output_mat, expected_mat):
  print("Correct output!\n")
else:
  print("Incorrect output!\n")

[[ 1. -1.  0.]
 [-1.  1. -1.]
 [ 0. -1.  1.]]
Correct output!



$input = 
\begin{pmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{pmatrix}
\,\,\,\,\,\,\,\,\,\,\,\,
kernel = 
\begin{pmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{pmatrix}$

In [42]:
# test case 4
input_mat = np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]])
kernel_mat = np.array([[1, 0, 0, 0],
                       [0, 1, 0, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]])
expected_mat = np.array([[4]])

output_mat = conv2d(input_mat, kernel_mat)

print(output_mat)
if np.array_equal(output_mat, expected_mat):
  print("Correct output!\n")
else:
  print("Incorrect output!\n")

[[4.]]
Correct output!



$input = 
\begin{pmatrix}
1 & -1\\
-1 & 0
\end{pmatrix}
\,\,\,\,\,\,\,\,\,\,\,\,
kernel = 
\begin{pmatrix}
1 & 0 & 0 & 0\\
0 & 1 & 0 & 0\\
0 & 0 & 1 & 0\\
0 & 0 & 0 & 1
\end{pmatrix}$

In [43]:
# test case 5 - should either through an error, or return empty matrix
input_mat = np.array([[1, -1],
                      [-1, 0]])
kernel_mat = np.array([[1, 0, 0, 0],
                       [0, 1, 0, 0],
                       [0, 0, 1, 0],
                       [0, 0, 0, 1]])
expected_mat = []

output_mat = conv2d(input_mat, kernel_mat)

# If an exception is raised, this is correct output.

ValueError: ignored

## Problem 2

A max pooling is performed on an inputted matrix with a window size of s. The max value in the given window size is retained and outputted for each possible window fitting on the matrix at one time. Columns or rows that do not fit within a window are dropped as per valid padding specifications.

In [0]:
# Applies a max pooling operation given a matrix and the window size.
def maxpooling2d(input_mat, s):
  # Catch empty inputs.
  if s == 0 or len(input_mat) == 0:
      raise ValueError('Empty input(s)')

  # Initialize.
  input_mat_width, input_mat_height  = len(input_mat[0]), len(input_mat)
  patch_width, patch_height  = s, s

  # Matrices must be square by the hw description.
  if input_mat_width != input_mat_height:
    raise ValueError('Matrix is not square')

  # Calculate output matrix dimensions.
  output_mat_width, output_mat_height = math.floor(input_mat_width/patch_width), math.floor(input_mat_height/patch_height)
  output_mat = np.zeros((output_mat_height, output_mat_width))

  # Apply max pooling.
  for i in range(output_mat_height):
    for j in range(output_mat_width):
      output_mat[i][j] = np.amax(input_mat[i*patch_height:i*patch_height+patch_height, j*patch_width:j*patch_width+patch_width])
  
  return output_mat

### Test cases

$input = 
\begin{pmatrix}
1 & 2 & 1 & 2\\
2 & 4 & 2 & 1\\
1 & 2 & 4 & 2\\
2 & 1 & 2 & 1
\end{pmatrix}
\,\,\,\,\,\,\,\,\,\,\,\,
s = 2$

In [45]:
# test case 1
input_mat = np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]])
s = 2
expected_mat = np.array([[4, 2],
                         [2, 4]])

output_mat = maxpooling2d(input_mat, s)

print(output_mat)
if np.array_equal(output_mat, expected_mat):
  print("Correct output!")
else:
  print("Incorrect output!")

[[4. 2.]
 [2. 4.]]
Correct output!


$input = 
\begin{pmatrix}
1 & 2 & 1 & 2 & 4 & 5\\
2 & 4 & 2 & 1 & 0 & 3\\
1 & 2 & 4 & 2 & 4 & 5\\
2 & 1 & 2 & 1 & 2 & 1\\
1 & 1 & 2 & 3 & 1 & 2\\
1 & 1 & 2 & 3 & 1 & 2
\end{pmatrix}
\,\,\,\,\,\,\,\,\,\,\,\,
s = 2$

In [46]:
# test case 2
input_mat = np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]])
s = 2
expected_mat = np.array([[4, 2, 5],
                         [2, 4, 5],
                         [1, 3, 2]])

output_mat = maxpooling2d(input_mat, s)

print(output_mat)
if np.array_equal(output_mat, expected_mat):
  print("Correct output!")
else:
  print("Incorrect output!")

[[4. 2. 5.]
 [2. 4. 5.]
 [1. 3. 2.]]
Correct output!


## Problem 3

Check out the two other Google Colabs that I submitted. They have the two CNNs.

This is some information about how I ended up with the classifier's architecture and configuration in HW_4_2:

When starting out, I tried testing different values in the existing Dense layer. I performed multiple tests and marked the accuracy of the network after a certain amount of time went. This allowed me to have a time-normalized benchmark in order to accurately determine the best layer configuration independent of varying epoch times.

I saved four of those tests. After 3 minutes, I found these results:    
Xception with dense_5 at 256: 178s loss: 0.3019 - acc: 0.8720 - val_loss: 0.0044 - val_acc: 0.9650    
Xception with dense_5 at 512: 183s loss: 0.3170 - acc: 0.8575 - val_loss: 0.0400 - val_acc: 0.9690    
Xception with dense_5 at 1024: 171s loss: 0.3155 - acc: 0.8685 - val_loss: 0.3426 - val_acc: 0.9520    
Xception with dense_5 at 2048: 172s loss: 0.3022 - acc: 0.8765 - val_loss: 5.0581e-05 - val_acc: 0.9670    

I settled on the configuration with the highest validation accuracy. Afterwards, I tested unfreezing different blocks in the Xception architecture for fine-tuning and found the most marked increase in unfreezing block12 of the Xception architecture.

I then moved on to the other CNN in HW_4_2 but I performed some additional research on classifiers. I found an example that used two Dense layers instead of one and said sometimes it was more effective than one with a binary classifier. After experimenting with some of those parameters, I settled on one Dense layer with 256 and another Dense layer with 128, resulting in the final HW_4_2 classifier.

# Citations

- https://setosa.io/ev/image-kernels/
- https://wiseodd.github.io/techblog/2016/07/18/convnet-maxpool-layer/
- https://github.com/schneider128k/machine_learning_course/blob/master/slides/images/cnn_architecture.png
- https://docs.scipy.org/doc/numpy/reference/generated/numpy.amax.html
- https://webcourses.ucf.edu/files/78844563/download?download_frd=1
